### ISSUE TITLE
KeyError: 'generate_fragments'

### ISSUE THREAD

**Issue by chengfengke** [howzh728/GRELinker#1]
Traceback (most recent call last):
  File "C:/Users/XPS/Desktop/GRELinker/pre-training/main.py", line 5, in <module>
    import util
  File "C:\Users\XPS\Desktop\GRELinker\pre-training\util.py", line 6, in <module>
    from tensorboard_writer import writer as tb_writer
  File "C:\Users\XPS\Desktop\GRELinker\pre-training\tensorboard_writer.py", line 5, in <module>
    from parameters.constants import constants as C
  File "C:\Users\XPS\Desktop\GRELinker\pre-training\parameters\constants.py", line 260, in <module>
    job_dir=args.job_dir)
  File "C:\Users\XPS\Desktop\GRELinker\pre-training\parameters\constants.py", line 221, in collect_global_constants
    constants_dict['generate_fragments'] = parameters["generate_fragments"]
KeyError: 'generate_fragments'

**Comment by kong0706** [comment]
I am reporting the same error as you, have you solved the problem yet?

**Comment by chengfengke** [comment]
> I am reporting the same error as you, have you solved the problem yet?

I restart the script again, and it seems that the error is gone.
* Preprocessing validation data.
-- 71856 molecules in set.
-- 2720684 total subgraphs in set.
Pay attention to the groundtruth datasets, they are misnamed.

**Comment by chengfengke** [comment]
> I am reporting the same error as you, have you solved the problem yet?

by the way, contact with me for further development, m13521952989@163.com

**Comment by kailash-acog** [comment]
> > I am reporting the same error as you, have you solved the problem yet?
> 
> I restart the script again, and it seems that the error is gone.
> 
> * Preprocessing validation data.
>   -- 71856 molecules in set.
>   -- 2720684 total subgraphs in set.
>   Pay attention to the groundtruth datasets, they are misnamed.

I restarted the script, but it is not working.
The error remain same :
File "/home/pre-training/parameters/constants.py", line 221, in collect_global_constants
    constants_dict['generate_fragments'] = parameters["generate_fragments"]
KeyError: 'generate_fragments'
